import type { Column, Row } from '../types'

// --- Column alignment map ---
function latexAlign(align: string) {
  if (align === 'center') return 'c'
  if (align === 'right') return 'r'
  return 'l'
}

// --- Escape special LaTeX characters ---
function escape(text: string) {
  return text
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}')
}

// --- Generate LaTeX tabularx code ---
export function exportLatex(
  columns: Column[],
  rows: Row[],
  title: string,
  filename = 'table'
) {
  const colSpec = columns.map((c) => latexAlign(c.align)).join(' | ')

  const header = columns.map((c) => `\\textbf{${escape(c.label)}}`).join(' & ')

  const body = rows.map((row) =>
    columns.map((col) => escape(row.cells[col.id] ?? '')).join(' & ')
  ).join(' \\\\\n  ')

  const latex = `% Generated by TableCraft
% Requires: \\usepackage{tabularx, booktabs, xcolor}

${title ? `\\textbf{${escape(title)}}\\\\[4pt]` : ''}
\\begin{tabular}{| ${colSpec} |}
\\hline
  ${header} \\\\
\\hline
  ${body} \\\\
\\hline
\\end{tabular}`

  const blob = new Blob([latex], { type: 'text/plain' })
  const link = document.createElement('a')
  link.download = `${filename}.tex`
  link.href = URL.createObjectURL(blob)
  link.click()
}